server:
    port: 8084
    
spring:
   application:
        name:  API-GATEWAY   
   config:
                import: optional:configserver:http://localhost:8085   
        
   cloud:
       gateway:
           routes:
             - id: USER-SERVICE
               uri: http://localhost:8081
               predicates:
                - Path=/users/**
               
             - id: HOTEL-SERVICE
               uri: http://localhost:8082
               predicates:
                   - Path=/hotels/**,/staffs/**
              
             - id: RATING-SERVICE
               uri: http://localhost:8083
               predicates:
                    - Path=/ratings/**          
#eureka:
#     instance:
#           prefer-ip-address: true
#            
#     client: 
#          register-with-eureka: true
#          fetch-registry: true
#          service-url: 
#               defaultZone: http://localhost:8761/eureka 
#               lease:
#                    duration: 5        